// NAUGATI Maritime Intelligence Platform - Canonical Demo Data
// Clearly marked as DEMO DATA with last updated timestamp.
// Designed for seamless replacement with external APIs (Baltic Exchange, AIS, Port Authorities, NOAA).

export const DATA_METADATA = {
  dataSource: "DEMO DATA (Simulated Maritime Intelligence Engine)",
  lastUpdated: "2026-09-13T12:00:00Z",
  refreshInterval: "15m",
  disclaimer: "Simulated market and AIS data for preview and algorithmic validation. Real-time feeds connect via NAUGATI API gateway."
};

// 7 Primary East Coast India Ports + International Origins
export const PORTS = [
  {
    id: "dhamra",
    name: "Dhamra Port",
    country: "India",
    state: "Odisha",
    unlocode: "IN DHM",
    coordinates: [86.9745, 20.8133], // [lng, lat]
    type: "Deep Water All-Weather Port",
    authority: "Dhamra Port Company Ltd (APSEZ)",
    maxDraft: 18.0, // meters
    maxLOA: 320, // meters
    maxBeam: 48, // meters
    maxVesselClass: "Capesize (up to 180,000 DWT)",
    berths: 5,
    berthLength: 1450,
    cargoHandlingCapacity: "45 MTPA",
    handlingRate: 45000, // MT/day
    currentCongestion: "Medium",
    congestionIndex: 58,
    waitingVessels: 4,
    averageWaitingTimeDays: 1.8,
    averageTurnaroundHours: 36,
    activeArrivals: 3,
    activeDepartures: 2,
    weatherStatus: "Normal (Sea State 2, Wind 12 kts SW)",
    weatherRisk: "Low",
    restrictions: "Draft tidal restrictions apply only for laden vessels >17.5m during neap tides.",
    congestionHistory: [
      { date: "09-07", waitingDays: 1.2, vessels: 3 },
      { date: "09-08", waitingDays: 1.4, vessels: 3 },
      { date: "09-09", waitingDays: 1.6, vessels: 4 },
      { date: "09-10", waitingDays: 2.1, vessels: 5 },
      { date: "09-11", waitingDays: 2.0, vessels: 5 },
      { date: "09-12", waitingDays: 1.9, vessels: 4 },
      { date: "09-13", waitingDays: 1.8, vessels: 4 },
    ]
  },
  {
    id: "paradip",
    name: "Paradip Port",
    country: "India",
    state: "Odisha",
    unlocode: "IN PRT",
    coordinates: [86.6713, 20.2644],
    type: "Major Port Trust",
    authority: "Paradip Port Authority",
    maxDraft: 14.5,
    maxLOA: 260,
    maxBeam: 42,
    maxVesselClass: "Panamax / Baby Capesize",
    berths: 16,
    berthLength: 3800,
    cargoHandlingCapacity: "140 MTPA",
    handlingRate: 35000,
    currentCongestion: "High",
    congestionIndex: 82,
    waitingVessels: 11,
    averageWaitingTimeDays: 3.4,
    averageTurnaroundHours: 58,
    activeArrivals: 8,
    activeDepartures: 5,
    weatherStatus: "Watch (Swell 2.1m, SW Wind 18 kts)",
    weatherRisk: "Medium",
    restrictions: "Vessels exceeding 14.5m draft must lighter at Sandheads before final berthing.",
    congestionHistory: [
      { date: "09-07", waitingDays: 2.8, vessels: 9 },
      { date: "09-08", waitingDays: 3.0, vessels: 10 },
      { date: "09-09", waitingDays: 3.2, vessels: 10 },
      { date: "09-10", waitingDays: 3.6, vessels: 12 },
      { date: "09-11", waitingDays: 3.5, vessels: 11 },
      { date: "09-12", waitingDays: 3.3, vessels: 11 },
      { date: "09-13", waitingDays: 3.4, vessels: 11 },
    ]
  },
  {
    id: "vizag",
    name: "Visakhapatnam (Vizag)",
    country: "India",
    state: "Andhra Pradesh",
    unlocode: "IN VTZ",
    coordinates: [83.2976, 17.6868],
    type: "Major Natural Deep Water Harbor",
    authority: "Visakhapatnam Port Authority",
    maxDraft: 16.5,
    maxLOA: 290,
    maxBeam: 45,
    maxVesselClass: "Capesize (Outer Harbor)",
    berths: 24,
    berthLength: 4600,
    cargoHandlingCapacity: "90 MTPA",
    handlingRate: 40000,
    currentCongestion: "Low",
    congestionIndex: 32,
    waitingVessels: 3,
    averageWaitingTimeDays: 1.1,
    averageTurnaroundHours: 32,
    activeArrivals: 5,
    activeDepartures: 4,
    weatherStatus: "Clear (Sea State 1, Wind 9 kts)",
    weatherRisk: "Low",
    restrictions: "Inner harbor restricted to 11.5m draft and 195m LOA. Outer berths accommodate full Capesize.",
    congestionHistory: [
      { date: "09-07", waitingDays: 1.4, vessels: 4 },
      { date: "09-08", waitingDays: 1.3, vessels: 3 },
      { date: "09-09", waitingDays: 1.1, vessels: 3 },
      { date: "09-10", waitingDays: 1.2, vessels: 3 },
      { date: "09-11", waitingDays: 1.0, vessels: 2 },
      { date: "09-12", waitingDays: 1.1, vessels: 3 },
      { date: "09-13", waitingDays: 1.1, vessels: 3 },
    ]
  },
  {
    id: "gangavaram",
    name: "Gangavaram Port",
    country: "India",
    state: "Andhra Pradesh",
    unlocode: "IN GGV",
    coordinates: [83.2356, 17.6183],
    type: "Private Deep Water Port",
    authority: "Adani Gangavaram Port Ltd",
    maxDraft: 20.0,
    maxLOA: 330,
    maxBeam: 50,
    maxVesselClass: "Capesize (up to 200,000 DWT)",
    berths: 9,
    berthLength: 2100,
    cargoHandlingCapacity: "64 MTPA",
    handlingRate: 55000,
    currentCongestion: "Low",
    congestionIndex: 28,
    waitingVessels: 2,
    averageWaitingTimeDays: 0.9,
    averageTurnaroundHours: 28,
    activeArrivals: 2,
    activeDepartures: 3,
    weatherStatus: "Clear (Sea State 1)",
    weatherRisk: "Low",
    restrictions: "Deepest all-weather multipurpose port in India. Minimal draft restrictions.",
    congestionHistory: [
      { date: "09-07", waitingDays: 0.8, vessels: 2 },
      { date: "09-08", waitingDays: 0.9, vessels: 2 },
      { date: "09-09", waitingDays: 1.0, vessels: 2 },
      { date: "09-10", waitingDays: 1.1, vessels: 3 },
      { date: "09-11", waitingDays: 0.9, vessels: 2 },
      { date: "09-12", waitingDays: 0.8, vessels: 2 },
      { date: "09-13", waitingDays: 0.9, vessels: 2 },
    ]
  },
  {
    id: "gopalpur",
    name: "Gopalpur Port",
    country: "India",
    state: "Odisha",
    unlocode: "IN GOP",
    coordinates: [84.9667, 19.3000],
    type: "Commercial All-Weather Port",
    authority: "Gopalpur Ports Limited",
    maxDraft: 13.0,
    maxLOA: 230,
    maxBeam: 36,
    maxVesselClass: "Supramax / Handymax",
    berths: 3,
    berthLength: 850,
    cargoHandlingCapacity: "20 MTPA",
    handlingRate: 22000,
    currentCongestion: "Medium",
    congestionIndex: 45,
    waitingVessels: 3,
    averageWaitingTimeDays: 2.1,
    averageTurnaroundHours: 46,
    activeArrivals: 2,
    activeDepartures: 1,
    weatherStatus: "Moderate Swell (Wind 14 kts)",
    weatherRisk: "Medium",
    restrictions: "Draft limit 13.0m. Night navigation permitted subject to pilotage.",
    congestionHistory: [
      { date: "09-07", waitingDays: 1.9, vessels: 2 },
      { date: "09-08", waitingDays: 2.0, vessels: 3 },
      { date: "09-09", waitingDays: 2.3, vessels: 3 },
      { date: "09-10", waitingDays: 2.4, vessels: 4 },
      { date: "09-11", waitingDays: 2.2, vessels: 3 },
      { date: "09-12", waitingDays: 2.0, vessels: 3 },
      { date: "09-13", waitingDays: 2.1, vessels: 3 },
    ]
  },
  {
    id: "sagar",
    name: "Sagar - Sandheads",
    country: "India",
    state: "West Bengal",
    unlocode: "IN SGR",
    coordinates: [88.0833, 21.6500],
    type: "Deep Water Anchorage / Transshipment",
    authority: "Syama Prasad Mookerjee Port Kolkata",
    maxDraft: 14.5,
    maxLOA: 260,
    maxBeam: 40,
    maxVesselClass: "Panamax (Lightering & Transshipment)",
    berths: 0, // Offshore anchorage
    berthLength: 0,
    cargoHandlingCapacity: "15 MTPA",
    handlingRate: 20000,
    currentCongestion: "Medium",
    congestionIndex: 52,
    waitingVessels: 5,
    averageWaitingTimeDays: 2.5,
    averageTurnaroundHours: 52,
    activeArrivals: 4,
    activeDepartures: 3,
    weatherStatus: "Tidal Swell (Tidal currents up to 4.5 kts)",
    weatherRisk: "Medium",
    restrictions: "Transshipment operations weather-dependent. Restricted during monsoon swells.",
    congestionHistory: [
      { date: "09-07", waitingDays: 2.2, vessels: 4 },
      { date: "09-08", waitingDays: 2.4, vessels: 5 },
      { date: "09-09", waitingDays: 2.7, vessels: 5 },
      { date: "09-10", waitingDays: 2.8, vessels: 6 },
      { date: "09-11", waitingDays: 2.6, vessels: 5 },
      { date: "09-12", waitingDays: 2.4, vessels: 5 },
      { date: "09-13", waitingDays: 2.5, vessels: 5 },
    ]
  },
  {
    id: "haldia",
    name: "Haldia Dock Complex",
    country: "India",
    state: "West Bengal",
    unlocode: "IN HAL",
    coordinates: [88.0644, 22.0289],
    type: "Enclosed Dock System (Lock Gate)",
    authority: "Syama Prasad Mookerjee Port Kolkata",
    maxDraft: 8.5, // Riverine / tide dependent
    maxLOA: 190,
    maxBeam: 30,
    maxVesselClass: "Handysize / Restricted Supramax",
    berths: 14,
    berthLength: 2600,
    cargoHandlingCapacity: "50 MTPA",
    handlingRate: 18000,
    currentCongestion: "High",
    congestionIndex: 88,
    waitingVessels: 9,
    averageWaitingTimeDays: 4.2,
    averageTurnaroundHours: 72,
    activeArrivals: 4,
    activeDepartures: 3,
    weatherStatus: "Riverine siltation watch. Draft governed by Hooghly river bar tides.",
    weatherRisk: "Medium",
    restrictions: "Strict river draft 7.5m - 8.5m. Panamax and Capesize cannot call without full lightering.",
    congestionHistory: [
      { date: "09-07", waitingDays: 3.8, vessels: 8 },
      { date: "09-08", waitingDays: 4.0, vessels: 8 },
      { date: "09-09", waitingDays: 4.4, vessels: 10 },
      { date: "09-10", waitingDays: 4.5, vessels: 10 },
      { date: "09-11", waitingDays: 4.3, vessels: 9 },
      { date: "09-12", waitingDays: 4.1, vessels: 9 },
      { date: "09-13", waitingDays: 4.2, vessels: 9 },
    ]
  }
];

// International Cargo Origins
export const ORIGINS = [
  {
    id: "australia",
    name: "Australia",
    ports: ["Hay Point", "Gladstone", "Newcastle", "Port Hedland"],
    defaultPort: "Hay Point",
    coordinates: [149.3000, -21.2833],
    commodities: ["Thermal Coal", "Coking Coal", "Iron Ore", "Bauxite"],
    baseDistanceNM: 4200,
    transitDaysAvg: 12.5,
    typicalVessel: "Capesize / Panamax",
    riskLevel: "Low",
    notes: "Direct route via Lombok / Sunda Strait into Bay of Bengal."
  },
  {
    id: "indonesia",
    name: "Indonesia",
    ports: ["Samarinda", "Balikpapan", "Taboneo", "Banjarmasin"],
    defaultPort: "Samarinda",
    coordinates: [117.1500, -0.5000],
    commodities: ["Thermal Coal", "Bauxite", "Nickel Ore"],
    baseDistanceNM: 2400,
    transitDaysAvg: 7.2,
    typicalVessel: "Supramax / Panamax",
    riskLevel: "Low",
    notes: "Transit via Malacca Strait or Sunda Strait; fast turnaround."
  },
  {
    id: "mozambique",
    name: "Mozambique",
    ports: ["Maputo", "Beira", "Nacala"],
    defaultPort: "Maputo",
    coordinates: [32.5833, -25.9667],
    commodities: ["Thermal Coal", "Titanium Minerals", "Graphite"],
    baseDistanceNM: 4600,
    transitDaysAvg: 14.0,
    typicalVessel: "Panamax / Supramax",
    riskLevel: "Medium",
    notes: "Cross Indian Ocean route; winter swell monitoring required."
  },
  {
    id: "russia",
    name: "Russia",
    ports: ["Taman", "Ust-Luga", "Vostochny"],
    defaultPort: "Taman",
    coordinates: [36.7000, 45.1333],
    commodities: ["Thermal Coal", "Fertilizers", "Metallurgical Coke"],
    baseDistanceNM: 6100,
    transitDaysAvg: 21.0,
    typicalVessel: "Panamax / Supramax",
    riskLevel: "High",
    notes: "Sanction compliance screening and Black Sea / Bosphorus transit delays."
  },
  {
    id: "us",
    name: "United States",
    ports: ["Hampton Roads", "Baltimore", "Mobile", "Houston"],
    defaultPort: "Hampton Roads",
    coordinates: [-76.3000, 36.9500],
    commodities: ["Coking Coal", "Petcoke", "Grain"],
    baseDistanceNM: 10400,
    transitDaysAvg: 32.0,
    typicalVessel: "Capesize / Panamax",
    riskLevel: "Medium",
    notes: "Route via Cape of Good Hope or Suez Canal."
  }
];

// Bulk Cargo Vessel Classes
export const VESSEL_CLASSES = [
  {
    type: "Handysize",
    dwtMin: 28000,
    dwtMax: 42000,
    dwtTypical: 38000,
    draftMax: 10.5,
    loaMax: 180,
    beamMax: 30,
    typicalSpeedKts: 13.0,
    fuelConsumptionBallastMT: 18,
    fuelConsumptionLadenMT: 22,
    dailyOperatingCost: 8500,
    suitablePorts: ["Dhamra", "Paradip", "Vizag", "Gangavaram", "Gopalpur", "Haldia", "Sagar-Sandheads"]
  },
  {
    type: "Supramax",
    dwtMin: 50000,
    dwtMax: 64000,
    dwtTypical: 58000,
    draftMax: 12.8,
    loaMax: 200,
    beamMax: 32.3,
    typicalSpeedKts: 13.5,
    fuelConsumptionBallastMT: 23,
    fuelConsumptionLadenMT: 28,
    dailyOperatingCost: 11200,
    suitablePorts: ["Dhamra", "Paradip", "Vizag", "Gangavaram", "Gopalpur", "Sagar-Sandheads"]
  },
  {
    type: "Panamax",
    dwtMin: 65000,
    dwtMax: 85000,
    dwtTypical: 76000,
    draftMax: 14.5,
    loaMax: 229,
    beamMax: 32.3,
    typicalSpeedKts: 14.0,
    fuelConsumptionBallastMT: 27,
    fuelConsumptionLadenMT: 34,
    dailyOperatingCost: 14500,
    suitablePorts: ["Dhamra", "Paradip", "Vizag", "Gangavaram", "Sagar-Sandheads"]
  },
  {
    type: "Capesize",
    dwtMin: 120000,
    dwtMax: 210000,
    dwtTypical: 180000,
    draftMax: 18.5,
    loaMax: 300,
    beamMax: 47,
    typicalSpeedKts: 14.2,
    fuelConsumptionBallastMT: 38,
    fuelConsumptionLadenMT: 48,
    dailyOperatingCost: 22000,
    suitablePorts: ["Dhamra", "Gangavaram", "Vizag (Outer)"]
  }
];

// Live Simulated Fleet
export const FLEET_VESSELS = [
  {
    id: "VES-101",
    name: "MV Ocean Splendor",
    imo: "9482110",
    flag: "Liberia",
    built: 2018,
    type: "Panamax",
    dwt: 76500,
    draft: 14.2,
    loa: 225.0,
    beam: 32.2,
    currentPosition: {
      lat: 5.82,
      lng: 85.34,
      locationName: "Bay of Bengal (Enroute to Dhamra)"
    },
    speed: 13.8,
    heading: 32,
    status: "Under Voyage",
    currentVoyage: "Gladstone -> Dhamra",
    nextPort: "Dhamra Port",
    destination: "Dhamra Port",
    eta: "2026-09-18 14:30",
    availabilityDate: "2026-09-22",
    availabilityStatus: "Available Soon",
    estimatedFreightUSDPerMT: 31.40,
    timeCharterUSDPerDay: 16800,
    deadheadingDistanceNM: 180,
    deadheadingCostUSD: 14200,
    fuelConsumptionLaden: 33.5,
    efficiencyScore: 94,
    compatibilityScore: 96,
    recommendationReason: "Direct draft compatibility with Dhamra (18m max vs 14.2m vessel). Repositioning window aligns with loading laycan.",
    owner: "Eastern Maritime Carriers"
  },
  {
    id: "VES-102",
    name: "MV Bharat Gaurav",
    imo: "9634921",
    flag: "India",
    built: 2020,
    type: "Capesize",
    dwt: 178000,
    draft: 17.8,
    loa: 292.0,
    beam: 45.0,
    currentPosition: {
      lat: -8.45,
      lng: 104.20,
      locationName: "Sunda Strait Entrance"
    },
    speed: 14.1,
    heading: 315,
    status: "Under Voyage",
    currentVoyage: "Port Hedland -> Gangavaram",
    nextPort: "Gangavaram Port",
    destination: "Gangavaram Port",
    eta: "2026-09-21 08:00",
    availabilityDate: "2026-09-25",
    availabilityStatus: "Available Soon",
    estimatedFreightUSDPerMT: 24.20,
    timeCharterUSDPerDay: 26500,
    deadheadingDistanceNM: 240,
    deadheadingCostUSD: 28500,
    fuelConsumptionLaden: 46.0,
    efficiencyScore: 96,
    compatibilityScore: 98,
    recommendationReason: "Deep-draft Capesize optimized for Gangavaram/Dhamra heavy coal shipments. Lowest unit transport cost.",
    owner: "Oceanic Bulk Shipping Ltd"
  },
  {
    id: "VES-103",
    name: "MV Kalinga Star",
    imo: "9518804",
    flag: "Singapore",
    built: 2017,
    type: "Supramax",
    dwt: 58000,
    draft: 12.6,
    loa: 190.0,
    beam: 32.2,
    currentPosition: {
      lat: 17.65,
      lng: 83.35,
      locationName: "Anchored off Visakhapatnam"
    },
    speed: 0.1,
    heading: 180,
    status: "Available",
    currentVoyage: "Discharged / In Ballast",
    nextPort: "Visakhapatnam Port",
    destination: "Open Position",
    eta: "Open Immediately",
    availabilityDate: "2026-09-14",
    availabilityStatus: "Immediate",
    estimatedFreightUSDPerMT: 36.80,
    timeCharterUSDPerDay: 13900,
    deadheadingDistanceNM: 45,
    deadheadingCostUSD: 3800,
    fuelConsumptionLaden: 27.5,
    efficiencyScore: 91,
    compatibilityScore: 92,
    recommendationReason: "Immediate spot availability in East Coast India; zero repositioning ballast time to Vizag or Gopalpur.",
    owner: "Pacific Bulk Line"
  },
  {
    id: "VES-104",
    name: "MV Southern Cross",
    imo: "9721098",
    flag: "Marshall Islands",
    built: 2021,
    type: "Panamax",
    dwt: 81200,
    draft: 14.4,
    loa: 228.9,
    beam: 32.2,
    currentPosition: {
      lat: 1.25,
      lng: 103.80,
      locationName: "Singapore East Anchorage"
    },
    speed: 12.4,
    heading: 300,
    status: "Under Voyage",
    currentVoyage: "Samarinda -> Paradip",
    nextPort: "Paradip Port",
    destination: "Paradip Port",
    eta: "2026-09-19 19:00",
    availabilityDate: "2026-09-24",
    availabilityStatus: "Available Soon",
    estimatedFreightUSDPerMT: 32.50,
    timeCharterUSDPerDay: 17200,
    deadheadingDistanceNM: 320,
    deadheadingCostUSD: 19800,
    fuelConsumptionLaden: 34.0,
    efficiencyScore: 93,
    compatibilityScore: 90,
    recommendationReason: "High-spec Kamsarmax with fuel-saving electronic engine, suitable for Paradip or Dhamra.",
    owner: "Global Tramp Chartering"
  },
  {
    id: "VES-105",
    name: "MV Utkal Pioneer",
    imo: "9390234",
    flag: "Panama",
    built: 2015,
    type: "Handysize",
    dwt: 35000,
    draft: 9.8,
    loa: 179.9,
    beam: 28.4,
    currentPosition: {
      lat: 21.90,
      lng: 88.02,
      locationName: "Haldia Anchorage"
    },
    speed: 0.0,
    heading: 45,
    status: "Discharging",
    currentVoyage: "Balikpapan -> Haldia",
    nextPort: "Haldia Dock Complex",
    destination: "Haldia Dock Complex",
    eta: "Discharging (ETA Open Sept 17)",
    availabilityDate: "2026-09-17",
    availabilityStatus: "Available Soon",
    estimatedFreightUSDPerMT: 42.10,
    timeCharterUSDPerDay: 10800,
    deadheadingDistanceNM: 80,
    deadheadingCostUSD: 5200,
    fuelConsumptionLaden: 21.0,
    efficiencyScore: 88,
    compatibilityScore: 100,
    recommendationReason: "Only draft class fully compliant with Haldia lock gates and river Hooghly shallow restrictions.",
    owner: "Bay Shipping Enterprise"
  },
  {
    id: "VES-106",
    name: "MV Bengal Queen",
    imo: "9563211",
    flag: "Liberia",
    built: 2019,
    type: "Panamax",
    dwt: 75200,
    draft: 14.1,
    loa: 224.5,
    beam: 32.2,
    currentPosition: {
      lat: -19.45,
      lng: 147.90,
      locationName: "Off Hay Point (Loading Coal)"
    },
    speed: 0.0,
    heading: 90,
    status: "Loading",
    currentVoyage: "Hay Point -> Dhamra",
    nextPort: "Hay Point Terminal",
    destination: "Dhamra Port",
    eta: "Departs 2026-09-15",
    availabilityDate: "2026-10-02",
    availabilityStatus: "Future Employment",
    estimatedFreightUSDPerMT: 30.90,
    timeCharterUSDPerDay: 16400,
    deadheadingDistanceNM: 0,
    deadheadingCostUSD: 0,
    fuelConsumptionLaden: 32.8,
    efficiencyScore: 95,
    compatibilityScore: 97,
    recommendationReason: "Currently berthed at coal loading terminal. Matches Australia-to-East Coast India benchmark.",
    owner: "Eastern Maritime Carriers"
  }
];

// Benchmark Market Indices
export const MARKET_INDICES = {
  balticDryIndex: {
    symbol: "BDI",
    name: "Baltic Dry Index",
    current: 2184,
    change: +72,
    changePercent: "+3.41%",
    trend: "Rising",
    status: "positive",
    historicalTrend: "Strong Q3 demand for iron ore & thermal coal"
  },
  balticCapesize: {
    symbol: "BCI",
    name: "Baltic Capesize Index",
    current: 3410,
    change: +145,
    changePercent: "+4.44%",
    trend: "Strong Bullish",
    status: "positive",
    averageTimeCharterUSD: 28250
  },
  balticPanamax: {
    symbol: "BPI",
    name: "Baltic Panamax Index",
    current: 1895,
    change: +32,
    changePercent: "+1.72%",
    trend: "Moderate Bullish",
    status: "positive",
    averageTimeCharterUSD: 17055
  },
  balticSupramax: {
    symbol: "BSI",
    name: "Baltic Supramax Index",
    current: 1430,
    change: -12,
    changePercent: "-0.83%",
    trend: "Consolidating",
    status: "warning",
    averageTimeCharterUSD: 14220
  },
  bunkerFuelVLSFO: {
    symbol: "VLSFO",
    name: "Very Low Sulphur Fuel Oil (Singapore)",
    current: 624.50,
    unit: "$/MT",
    change: -5.20,
    changePercent: "-0.82%",
    trend: "Softening",
    status: "positive"
  },
  thermalCoalNewcastle: {
    symbol: "NEWC",
    name: "Newcastle 6000 kcal Coal",
    current: 138.20,
    unit: "$/MT FOB",
    change: +1.80,
    changePercent: "+1.32%",
    trend: "Firming",
    status: "neutral"
  },
  ironOre62Fe: {
    symbol: "IO62",
    name: "Iron Ore Fines 62% Fe CFR China",
    current: 104.70,
    unit: "$/DMT",
    change: +0.90,
    changePercent: "+0.87%",
    trend: "Stable",
    status: "neutral"
  }
};

// Historical and Forecast Freight Time Series Data
export const FREIGHT_TIME_SERIES = [
  // 60-day historical window
  { date: "2026-07-15", actual: 26.50, forecast: null, upper: null, lower: null, bdi: 1840 },
  { date: "2026-07-22", actual: 27.20, forecast: null, upper: null, lower: null, bdi: 1880 },
  { date: "2026-07-29", actual: 27.80, forecast: null, upper: null, lower: null, bdi: 1920 },
  { date: "2026-08-05", actual: 28.40, forecast: null, upper: null, lower: null, bdi: 1960 },
  { date: "2026-08-12", actual: 29.10, forecast: null, upper: null, lower: null, bdi: 2010 },
  { date: "2026-08-19", actual: 29.90, forecast: null, upper: null, lower: null, bdi: 2075 },
  { date: "2026-08-26", actual: 30.20, forecast: null, upper: null, lower: null, bdi: 2110 },
  { date: "2026-09-02", actual: 30.80, forecast: null, upper: null, lower: null, bdi: 2140 },
  { date: "2026-09-09", actual: 31.00, forecast: null, upper: null, lower: null, bdi: 2165 },
  // Current pivot point
  { date: "2026-09-13", actual: 31.40, forecast: 31.40, upper: 31.40, lower: 31.40, bdi: 2184, isCurrent: true },
  // 7D Forecast
  { date: "2026-09-20", actual: null, forecast: 32.30, upper: 33.10, lower: 31.50, bdi: 2220 },
  // 14D Forecast
  { date: "2026-09-27", actual: null, forecast: 33.15, upper: 34.30, lower: 32.00, bdi: 2260 },
  // 30D Forecast
  { date: "2026-10-13", actual: null, forecast: 34.50, upper: 36.20, lower: 32.80, bdi: 2340 },
  // 60D Forecast
  { date: "2026-11-13", actual: null, forecast: 35.80, upper: 38.10, lower: 33.50, bdi: 2420 },
  // 90D Forecast
  { date: "2026-12-13", actual: null, forecast: 36.40, upper: 39.40, lower: 33.80, bdi: 2460 }
];

// Machine Learning Model Benchmark Data
export const ML_MODEL_BENCHMARKS = [
  {
    model: "XGBoost (Feature Engineered Regressor)",
    type: "Primary Production Model",
    mae: 0.68,
    rmse: 0.94,
    mape: "2.41%",
    directionalAccuracy: "88.6%",
    features: "Lags 1,3,7,14,30, Rolling Std/Mean, Bunker Price, Coal Index, Port Congestion Index, Vessel Supply"
  },
  {
    model: "SARIMA (Seasonal Benchmark)",
    type: "Statistical Baseline",
    mae: 1.15,
    rmse: 1.52,
    mape: "3.92%",
    directionalAccuracy: "79.2%",
    features: "(1,1,1)x(1,1,0)[7] on Log-differenced freight series"
  },
  {
    model: "Naive Drift Model",
    type: "Control Baseline",
    mae: 2.30,
    rmse: 2.85,
    mape: "7.80%",
    directionalAccuracy: "52.0%",
    features: "Random Walk with Historical Drift"
  }
];

// Multi-Criteria Route Optimization Data
export const ROUTE_OPTIONS = [
  {
    id: "route-rec",
    title: "Route A: Sunda Strait Direct (Recommended)",
    origin: "Hay Point, Australia",
    destination: "Dhamra Port, India",
    distanceNM: 4120,
    voyageDays: 12.3,
    speedKts: 14.0,
    fuelConsumptionMT: 412,
    estimatedFuelCostUSD: 257088,
    totalVoyageCostUSD: 442000,
    weatherRisk: "Low (Monsoon swell subside)",
    congestionRisk: "Low",
    geopoliticalRisk: "Low (No choke-point sanctions)",
    overallRisk: "Low",
    score: 94,
    status: "recommended",
    description: "Optimal balance of distance and deep-water safety avoiding Malacca Strait traffic.",
    waypoints: [
      { name: "Hay Point Departure", lat: -21.28, lng: 149.30 },
      { name: "Torres Strait Deep Water Pass", lat: -10.50, lng: 142.10 },
      { name: "Arafura Sea Waypoint", lat: -8.80, lng: 133.50 },
      { name: "Timor Sea Passage", lat: -9.50, lng: 124.20 },
      { name: "Sunda Strait Deep Water", lat: -6.00, lng: 105.80 },
      { name: "Equator Crossing Indian Ocean", lat: 0.00, lng: 94.50 },
      { name: "Bay of Bengal Center", lat: 12.50, lng: 88.00 },
      { name: "Dhamra Pilot Station", lat: 20.81, lng: 86.97 }
    ]
  },
  {
    id: "route-alt",
    title: "Route B: Malacca Strait Highway (Alternative)",
    origin: "Hay Point, Australia",
    destination: "Dhamra Port, India",
    distanceNM: 4380,
    voyageDays: 13.1,
    speedKts: 14.0,
    fuelConsumptionMT: 442,
    estimatedFuelCostUSD: 275808,
    totalVoyageCostUSD: 469500,
    weatherRisk: "Low",
    congestionRisk: "High (Malacca Strait Traffic Density >220 vessels/day)",
    geopoliticalRisk: "Medium",
    overallRisk: "Medium",
    score: 82,
    status: "alternative",
    description: "Standard commercial route via Singapore bunkering hub; higher traffic and piracy watch zone.",
    waypoints: [
      { name: "Hay Point Departure", lat: -21.28, lng: 149.30 },
      { name: "Coral Sea Waypoint", lat: -15.00, lng: 148.00 },
      { name: "Lombok Strait", lat: -8.70, lng: 115.70 },
      { name: "Java Sea Corridor", lat: -4.50, lng: 110.00 },
      { name: "Singapore Strait TSS", lat: 1.25, lng: 103.80 },
      { name: "Malacca Strait North Gate", lat: 5.50, lng: 97.50 },
      { name: "Nicobar Channel", lat: 8.00, lng: 93.50 },
      { name: "Dhamra Pilot Station", lat: 20.81, lng: 86.97 }
    ]
  },
  {
    id: "route-short",
    title: "Route C: Great Barrier North Pass (Shortcut)",
    origin: "Hay Point, Australia",
    destination: "Dhamra Port, India",
    distanceNM: 3980,
    voyageDays: 12.1,
    speedKts: 13.7, // Speed restricted in reef channels
    fuelConsumptionMT: 395,
    estimatedFuelCostUSD: 246480,
    totalVoyageCostUSD: 431000,
    weatherRisk: "Medium (Shallow reef tides)",
    congestionRisk: "Medium (Mandatory pilotage queue)",
    geopoliticalRisk: "Low",
    overallRisk: "Medium",
    score: 86,
    status: "shortcut",
    description: "Shortest nautical distance but requires mandatory Torres Strait pilotage and speed reduction.",
    waypoints: [
      { name: "Hay Point Departure", lat: -21.28, lng: 149.30 },
      { name: "Inner Reef Track", lat: -16.20, lng: 146.00 },
      { name: "Prince of Wales Channel", lat: -10.50, lng: 142.20 },
      { name: "Banda Sea Track", lat: -5.00, lng: 128.00 },
      { name: "Lombok North Route", lat: -7.50, lng: 116.50 },
      { name: "Indian Ocean Direct", lat: 6.00, lng: 90.00 },
      { name: "Dhamra Pilot Station", lat: 20.81, lng: 86.97 }
    ]
  }
];

// Shipowner Deadheading & Backhaul Cargo Opportunities
export const BACKHAUL_OPPORTUNITIES = [
  {
    id: "OPP-301",
    cargo: "Iron Ore Fines",
    quantity: "70,000 MT",
    origin: "Paradip / Dhamra, India",
    destination: "Qingdao, China",
    laycan: "2026-09-24 - 2026-09-28",
    offeredFreightUSDPerMT: 14.80,
    repositioningDistanceNM: 45,
    ballastTimeHours: 4,
    estimatedRevenueUSD: 1036000,
    estimatedVoyageCostUSD: 610000,
    netMarginUSD: 426000,
    dailyTCEUSD: 23660,
    risk: "Low",
    confidence: "High",
    status: "Recommended Spot Backhaul",
    matchScore: 95
  },
  {
    id: "OPP-302",
    cargo: "Thermal Coal",
    quantity: "65,000 MT",
    origin: "Samarinda, Indonesia",
    destination: "Visakhapatnam, India",
    laycan: "2026-09-28 - 2026-10-04",
    offeredFreightUSDPerMT: 11.20,
    repositioningDistanceNM: 310,
    ballastTimeHours: 24,
    estimatedRevenueUSD: 728000,
    estimatedVoyageCostUSD: 430000,
    netMarginUSD: 298000,
    dailyTCEUSD: 19860,
    risk: "Medium",
    confidence: "Medium",
    status: "Triangulation Opportunity",
    matchScore: 88
  },
  {
    id: "OPP-303",
    cargo: "Ilmenite & Bauxite",
    quantity: "50,000 MT",
    origin: "Gopalpur, India",
    destination: "Port Klang, Malaysia",
    laycan: "2026-09-22 - 2026-09-26",
    offeredFreightUSDPerMT: 13.50,
    repositioningDistanceNM: 60,
    ballastTimeHours: 5,
    estimatedRevenueUSD: 675000,
    estimatedVoyageCostUSD: 395000,
    netMarginUSD: 280000,
    dailyTCEUSD: 20000,
    risk: "Low",
    confidence: "High",
    status: "Short-Haul Backhaul",
    matchScore: 92
  }
];

// Active Maritime Alerts
export const MARITIME_ALERTS = [
  {
    id: "ALT-01",
    title: "Freight Rate Surge Alert: Australia -> East Coast India",
    severity: "critical",
    category: "Freight",
    description: "Cape & Panamax rates on Newcastle/Hay Point to Dhamra route forecast to rise +$2.80/MT over 14 days due to Australian rail maintenance and Indian festive stock building.",
    timestamp: "10 mins ago",
    relatedPort: "Dhamra Port",
    relatedRoute: "Hay Point -> Dhamra",
    recommendedAction: "Lock in voyage charter or 3-month contract promptly."
  },
  {
    id: "ALT-02",
    title: "Port Congestion Warning: Paradip Port",
    severity: "warning",
    category: "Port",
    description: "Waiting time at Paradip mechanised coal berths surged to 3.4 days with 11 bulk carriers queued at anchorage. Berth utilization at 92%.",
    timestamp: "45 mins ago",
    relatedPort: "Paradip Port",
    recommendedAction: "Consider diverting Panamax shipments to Dhamra (1.8 days waiting) or Gangavaram (0.9 days waiting)."
  },
  {
    id: "ALT-03",
    title: "Weather Swell Watch: Southern Bay of Bengal",
    severity: "info",
    category: "Weather",
    description: "Southwest monsoon low pressure trough causing 2.5m swells south of Sri Lanka. Expect +0.5 days transit time for Mozambique & South Africa origins.",
    timestamp: "2 hours ago",
    relatedRoute: "Maputo -> Vizag",
    recommendedAction: "Maintain weather routing track 60 NM east of standard path."
  },
  {
    id: "ALT-04",
    title: "Backhaul Iron Ore Fixture Match: Dhamra -> Qingdao",
    severity: "info",
    category: "Contract",
    description: "New 70,000 MT iron ore fixture available at $14.80/MT loading Sept 25. High margin ($426k net) for discharging Panamaxes in Odisha.",
    timestamp: "3 hours ago",
    relatedPort: "Dhamra Port",
    recommendedAction: "Review and accept backhaul fixture to reduce deadheading ballast cost."
  }
];
